# D1：Numpy 陣列的定義與屬性
***

# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [9]:
'''
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。
'''
import numpy as np

a = np.random.randint(10, size=6)

print('list(a):', list(a))
print('a.tolist():', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b):',list(b))
print('b.tolist():', b.tolist())

list(a): [2, 8, 1, 4, 4, 7]
a.tolist(): [2, 8, 1, 4, 4, 7]
list(b): [array([1, 7]), array([9, 2]), array([0, 4])]
b.tolist(): [[1, 7], [9, 2], [0, 4]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
'''
print(a)    # 印出 NdArray 的內容值
print(a.ndim)   # 印出 NdArray 有多少維度
print(a.shape)   # 印出 NdArray 每個維度的大小
print(a.size)   # 印出 NdArray 中有幾個元素
print(a.dtype)  # 印出 NdArray 的資料型態
print(a.itemsize)   # 印出 NdArray 每個元素佔用的空間
print(len(a))   # 印出 NdArray 的長度
print(type(a))  # 印出 NdArray 的類型
'''
import numpy as np
a = np.random.randint(10, size=6)

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))
print('-------------')

'''
print(b)    # 印出 NdArray 的內容值
print(b.ndim)   # 印出 NdArray 有多少維度
print(b.shape)   # 印出 NdArray 每個維度的大小
print(b.size)   # 印出 NdArray 中有幾個元素
print(b.dtype)  # 印出 NdArray 的資料型態
print(b.itemsize)   # 印出 NdArray 每個元素佔用的空間
print(len(b))   # 印出 NdArray 第一層的長度
print(type(b))  # 印出 NdArray 的類型
'''
b = np.random.randint(10, size=(3,4))

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
print('-------------')

'''
print(c)    # 印出 NdArray 的內容值
print(c.ndim)   # 印出 NdArray 有多少維度
print(c.shape)   # 印出 NdArray 每個維度的大小
print(c.size)   # 印出 NdArray 中有幾個元素
print(c.dtype)  # 印出 NdArray 的資料型態
print(c.itemsize)   # 印出 NdArray 每個元素佔用的空間
print(len(c))   # 印出 NdArray 第一層的長度
print(type(c))  # 印出 NdArray 的類型
'''
c= np.random.randint(10, size=(2,3,2))

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[1 4 2 3 0 7]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>
-------------
[[2 7 1 6]
 [4 1 2 5]
 [5 9 3 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>
-------------
[[[3 2]
  [0 2]
  [2 7]]

 [[0 0]
  [4 7]
  [5 6]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [5]:
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4))
c= np.random.randint(10, size=(2,3,2))

##簡單版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 4, 0, 5, 0, 0]
[[1, 5, 3, 2], [8, 0, 3, 7], [4, 5, 7, 3]]
[[[1, 8], [1, 1], [4, 8]], [[9, 3], [8, 9], [0, 5]]]


In [7]:
##進階版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 4, 0, 5, 0, 0]
[[1, 5, 3, 2], [8, 0, 3, 7], [4, 5, 7, 3]]
[[[1, 8], [1, 1], [4, 8]], [[9, 3], [8, 9], [0, 5]]]
