# D1：Numpy 陣列的定義與屬性
***

# [教學目標]

* 認識 Numpy 套件與 Array 陣列定義
* 正確使用 Array 的常用屬性
* 能夠掌握 Array 的重要特性


In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\seask\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.2


In [2]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 陣列的常用屬性

print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('data: ', a.data)


ndim:  2
shape:  (3, 5)
size:  15
dtype:  int32
itemsize:  4
data:  <memory at 0x0000015B2466F790>


In [4]:
# List 與 Array 的轉換

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


# [Homework]

In [9]:
# Homework1:請問下列兩種將 Array 轉換成 List 的方式有何不同？
import numpy as np

a = np.random.randint(10, size=6)

print('list(a):', list(a))
print('a.tolist():', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b):',list(b))
print('b.tolist():', b.tolist())

list(a): [2, 8, 1, 4, 4, 7]
a.tolist(): [2, 8, 1, 4, 4, 7]
list(b): [array([1, 7]), array([9, 2]), array([0, 4])]
b.tolist(): [[1, 7], [9, 2], [0, 4]]


In [13]:
# Homework2:請試著在程式中印出以下三個 NdArray 的屬性？
#（屬性：ndim、shape、size、dtype、itemsize、length、type）
import numpy as np
a = np.random.randint(10, size=6)

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))
print('-------------')

b = np.random.randint(10, size=(3,4))

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
print('-------------')

c= np.random.randint(10, size=(2,3,2))

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[4 2 2 2 2 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>
-------------
[[8 1 9 9]
 [6 3 6 5]
 [2 0 2 6]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>
-------------
[[[6 6]
  [6 3]
  [1 7]]

 [[8 1]
  [7 8]
  [9 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [18]:
# 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=(3,4))
c= np.random.randint(10, size=(2,3,2))

##簡單版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 5, 5, 1, 0, 2]
[[0, 1, 6, 4], [2, 8, 8, 9], [4, 0, 0, 1]]
[[[1, 4], [2, 0], [6, 8]], [[0, 8], [4, 2], [2, 6]]]
-------------


In [19]:
##進階版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 5, 5, 1, 0, 2]
[[0, 1, 6, 4], [2, 8, 8, 9], [4, 0, 0, 1]]
[[[1, 4], [2, 0], [6, 8]], [[0, 8], [4, 2], [2, 6]]]
