# D3：Numpy 陣列的初始化
***

# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
'''
np.zeros((2,3))會產生真正的0；np.empty((2,3))會產生一個近似於0的陣列。
np.empty可以用於只是想要初始化，但之後就會數值複寫過的狀況。
'''

'\nnp.zeros((2,3))會產生真正的0；np.empty((2,3))會產生一個近似於0的陣列。\nnp.empty可以用於只是想要初始化，但之後就會數值複寫過的狀況。\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 記得先 Import 正確的套件

import numpy as np

a = np.random.rand(2,3)
a = a * 100

print(a)

[[89.52812965 75.53250948 60.51380411]
 [59.11016627 21.72323502  8.75100655]]


In [5]:
# 參考解答

print(a.round())
print(np.round(a))

[[90. 76. 61.]
 [59. 22.  9.]]
[[90. 76. 61.]
 [59. 22.  9.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [6]:
m = 20
n = 40

a = np.random.rand(2,3) * (n-m)
b = a

print((a - b % 1) + m)

[[25. 22. 26.]
 [26. 29. 26.]]
